[package]
name = "parallel-sort"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Shavrov <alexander.shavrov@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
rand = "0.8.5"